USE cargoconnect_db;

SET @admin_user_id = (SELECT id FROM users WHERE username = 'admin');

INSERT INTO shipments (
  shipment_code,
  customer_id,
  category_id,
  pickup_address,
  pickup_city,
  pickup_state,
  pickup_postal_code,
  delivery_address,
  delivery_city,
  delivery_state,
  delivery_postal_code,
  receiver_name,
  receiver_phone,
  package_type,
  package_weight_kg,
  vehicle_preference,
  is_fragile,
  delivery_notes,
  scheduled_pickup_at,
  estimated_distance_km,
  estimated_duration_minutes,
  estimated_price,
  shipment_status,
  payment_status,
  approved_by_user_id,
  approved_at
) VALUES
  (
    'SHP-2026-0006',
    (SELECT id FROM customers WHERE customer_code = 'CUST-TEST'),
    (SELECT id FROM shipment_categories WHERE code = 'medium_goods'),
    'CargoConnect Test Warehouse, Mumbai, Maharashtra 400001',
    'Mumbai',
    'Maharashtra',
    '400001',
    'CargoConnect Test Receiver, Thane, Maharashtra 400601',
    'Thane',
    'Maharashtra',
    '400601',
    'CargoConnect Test Receiver',
    '+919811119999',
    'Test cartons',
    45.00,
    'mini_truck',
    0,
    'Seeded assigned shipment for driver flow testing.',
    '2026-05-06 11:00:00',
    24.50,
    70,
    1283.00,
    'assigned',
    'paid',
    @admin_user_id,
    CURRENT_TIMESTAMP
  ),
  (
    'SHP-2026-0001',
    (SELECT id FROM customers WHERE customer_code = 'CUST-0001'),
    (SELECT id FROM shipment_categories WHERE code = 'small_parcel'),
    'Bandra Kurla Complex, Mumbai, Maharashtra 400051',
    'Mumbai',
    'Maharashtra',
    '400051',
    'Lower Parel, Mumbai, Maharashtra 400013',
    'Mumbai',
    'Maharashtra',
    '400013',
    'Meera Joshi',
    '+919811110001',
    'Documents',
    2.50,
    'bike',
    0,
    'Call receiver before arrival.',
    '2026-05-02 10:30:00',
    14.20,
    45,
    405.00,
    'pending',
    'unpaid',
    NULL,
    NULL
  ),
  (
    'SHP-2026-0002',
    (SELECT id FROM customers WHERE customer_code = 'CUST-0002'),
    (SELECT id FROM shipment_categories WHERE code = 'refrigerated'),
    'Indiranagar, Bengaluru, Karnataka 560038',
    'Bengaluru',
    'Karnataka',
    '560038',
    'Koramangala, Bengaluru, Karnataka 560095',
    'Bengaluru',
    'Karnataka',
    '560095',
    'FreshMart Receiving',
    '+919811110002',
    'Cold-chain cartons',
    420.00,
    'refrigerated_truck',
    0,
    'Maintain chilled handling.',
    '2026-05-03 08:00:00',
    11.80,
    40,
    1912.60,
    'approved',
    'pending',
    @admin_user_id,
    CURRENT_TIMESTAMP
  ),
  (
    'SHP-2026-0003',
    (SELECT id FROM customers WHERE customer_code = 'CUST-0003'),
    (SELECT id FROM shipment_categories WHERE code = 'fragile'),
    'Connaught Place, New Delhi, Delhi 110001',
    'New Delhi',
    'Delhi',
    '110001',
    'Gurugram Sector 44, Haryana 122003',
    'Gurugram',
    'Haryana',
    '122003',
    'Aditi Rao',
    '+919811110003',
    'Electronics',
    35.00,
    'van',
    1,
    'Use protective handling.',
    '2026-05-04 14:00:00',
    31.50,
    75,
    1896.00,
    'assigned',
    'paid',
    @admin_user_id,
    CURRENT_TIMESTAMP
  ),
  (
    'SHP-2026-0004',
    (SELECT id FROM customers WHERE customer_code = 'CUST-0001'),
    (SELECT id FROM shipment_categories WHERE code = 'heavy_cargo'),
    'Navi Mumbai MIDC, Maharashtra 400710',
    'Navi Mumbai',
    'Maharashtra',
    '400710',
    'Pune Chakan Industrial Area, Maharashtra 410501',
    'Pune',
    'Maharashtra',
    '410501',
    'Warehouse Dock 4',
    '+919811110004',
    'Machine parts',
    1800.00,
    'heavy_truck',
    0,
    'Forklift required at destination.',
    '2026-05-05 06:30:00',
    145.00,
    230,
    9909.00,
    'in_transit',
    'paid',
    @admin_user_id,
    CURRENT_TIMESTAMP
  ),
  (
    'SHP-2026-0005',
    (SELECT id FROM customers WHERE customer_code = 'CUST-0002'),
    (SELECT id FROM shipment_categories WHERE code = 'urgent'),
    'MG Road, Bengaluru, Karnataka 560001',
    'Bengaluru',
    'Karnataka',
    '560001',
    'Electronic City, Bengaluru, Karnataka 560100',
    'Bengaluru',
    'Karnataka',
    '560100',
    'Ops Control Desk',
    '+919811110005',
    'Priority equipment',
    68.00,
    'mini_truck',
    1,
    'Priority delivery window.',
    '2026-05-01 09:15:00',
    22.70,
    60,
    1988.60,
    'completed',
    'paid',
    @admin_user_id,
    CURRENT_TIMESTAMP
  )
ON DUPLICATE KEY UPDATE
  customer_id = VALUES(customer_id),
  category_id = VALUES(category_id),
  pickup_address = VALUES(pickup_address),
  delivery_address = VALUES(delivery_address),
  receiver_name = VALUES(receiver_name),
  receiver_phone = VALUES(receiver_phone),
  package_type = VALUES(package_type),
  package_weight_kg = VALUES(package_weight_kg),
  vehicle_preference = VALUES(vehicle_preference),
  is_fragile = VALUES(is_fragile),
  delivery_notes = VALUES(delivery_notes),
  scheduled_pickup_at = VALUES(scheduled_pickup_at),
  estimated_distance_km = VALUES(estimated_distance_km),
  estimated_duration_minutes = VALUES(estimated_duration_minutes),
  estimated_price = VALUES(estimated_price),
  shipment_status = VALUES(shipment_status),
  payment_status = VALUES(payment_status),
  approved_by_user_id = VALUES(approved_by_user_id),
  approved_at = VALUES(approved_at),
  deleted_at = NULL;

INSERT INTO assignments (
  assignment_code,
  shipment_id,
  driver_id,
  vehicle_id,
  assigned_by_user_id,
  assignment_status
) VALUES
  (
    'ASN-2026-TEST',
    (SELECT id FROM shipments WHERE shipment_code = 'SHP-2026-0006'),
    (SELECT id FROM drivers WHERE driver_code = 'DRV-TEST'),
    (SELECT id FROM vehicles WHERE vehicle_number = 'CC-TEST-0001'),
    @admin_user_id,
    'assigned'
  )
ON DUPLICATE KEY UPDATE
  shipment_id = VALUES(shipment_id),
  driver_id = VALUES(driver_id),
  vehicle_id = VALUES(vehicle_id),
  assigned_by_user_id = VALUES(assigned_by_user_id),
  assignment_status = VALUES(assignment_status),
  deleted_at = NULL;

INSERT INTO support_issues (
  issue_code,
  customer_id,
  shipment_id,
  issue_type,
  priority,
  subject,
  description,
  issue_status
) VALUES
  (
    'SUP-2026-TEST',
    (SELECT id FROM customers WHERE customer_code = 'CUST-TEST'),
    (SELECT id FROM shipments WHERE shipment_code = 'SHP-2026-0006'),
    'delay',
    'medium',
    'Need pickup timing confirmation',
    'Please confirm the final pickup window for this assigned test shipment.',
    'open'
  )
ON DUPLICATE KEY UPDATE
  customer_id = VALUES(customer_id),
  shipment_id = VALUES(shipment_id),
  issue_type = VALUES(issue_type),
  priority = VALUES(priority),
  subject = VALUES(subject),
  description = VALUES(description),
  issue_status = VALUES(issue_status),
  deleted_at = NULL;

INSERT INTO feedback (
  feedback_code,
  customer_id,
  shipment_id,
  rating,
  experience_tags,
  comments,
  would_recommend
) VALUES
  (
    'FDB-2026-TEST',
    (SELECT id FROM customers WHERE customer_code = 'CUST-TEST'),
    (SELECT id FROM shipments WHERE shipment_code = 'SHP-2026-0006'),
    5,
    JSON_ARRAY('professional', 'clear_updates'),
    'Seeded feedback for customer API testing.',
    1
  )
ON DUPLICATE KEY UPDATE
  rating = VALUES(rating),
  experience_tags = VALUES(experience_tags),
  comments = VALUES(comments),
  would_recommend = VALUES(would_recommend),
  deleted_at = NULL;
