USE cargoconnect_db;

CREATE TABLE IF NOT EXISTS drivers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  driver_code VARCHAR(40) NOT NULL,
  license_number VARCHAR(80) NOT NULL,
  license_expiry_date DATE NOT NULL,
  address_line1 VARCHAR(180) NULL,
  address_line2 VARCHAR(180) NULL,
  city VARCHAR(100) NULL,
  state VARCHAR(100) NULL,
  postal_code VARCHAR(20) NULL,
  availability_status VARCHAR(20) NOT NULL DEFAULT 'available',
  driver_status VARCHAR(20) NOT NULL DEFAULT 'active',
  rating DECIMAL(3,2) NOT NULL DEFAULT 0.00,
  completed_trips INT UNSIGNED NOT NULL DEFAULT 0,
  emergency_contact_name VARCHAR(120) NULL,
  emergency_contact_phone VARCHAR(30) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_drivers_user_id (user_id),
  UNIQUE KEY uq_drivers_driver_code (driver_code),
  UNIQUE KEY uq_drivers_license_number (license_number),
  KEY idx_drivers_availability_status (availability_status),
  KEY idx_drivers_driver_status (driver_status),
  KEY idx_drivers_license_expiry_date (license_expiry_date),
  KEY idx_drivers_deleted_at (deleted_at),
  CONSTRAINT fk_drivers_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_drivers_availability_status CHECK (availability_status IN ('available', 'busy', 'offline', 'on_leave')),
  CONSTRAINT chk_drivers_driver_status CHECK (driver_status IN ('active', 'inactive', 'suspended')),
  CONSTRAINT chk_drivers_rating CHECK (rating >= 0.00 AND rating <= 5.00)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
