USE cargoconnect_db;

CREATE TABLE IF NOT EXISTS shipments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  shipment_code VARCHAR(40) NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  pickup_address TEXT NOT NULL,
  pickup_city VARCHAR(100) NULL,
  pickup_state VARCHAR(100) NULL,
  pickup_postal_code VARCHAR(20) NULL,
  pickup_latitude DECIMAL(10,7) NULL,
  pickup_longitude DECIMAL(10,7) NULL,
  delivery_address TEXT NOT NULL,
  delivery_city VARCHAR(100) NULL,
  delivery_state VARCHAR(100) NULL,
  delivery_postal_code VARCHAR(20) NULL,
  delivery_latitude DECIMAL(10,7) NULL,
  delivery_longitude DECIMAL(10,7) NULL,
  receiver_name VARCHAR(120) NOT NULL,
  receiver_phone VARCHAR(30) NOT NULL,
  package_type VARCHAR(80) NOT NULL,
  package_weight_kg DECIMAL(10,2) NOT NULL,
  package_length_cm DECIMAL(10,2) NULL,
  package_width_cm DECIMAL(10,2) NULL,
  package_height_cm DECIMAL(10,2) NULL,
  vehicle_preference VARCHAR(30) NULL,
  is_fragile TINYINT(1) NOT NULL DEFAULT 0,
  delivery_notes TEXT NULL,
  scheduled_pickup_at DATETIME NOT NULL,
  estimated_distance_km DECIMAL(10,2) NULL,
  estimated_duration_minutes INT UNSIGNED NULL,
  estimated_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  shipment_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
  approved_by_user_id BIGINT UNSIGNED NULL,
  approved_at TIMESTAMP NULL DEFAULT NULL,
  cancelled_by_user_id BIGINT UNSIGNED NULL,
  cancelled_at TIMESTAMP NULL DEFAULT NULL,
  cancellation_reason VARCHAR(255) NULL,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_shipments_shipment_code (shipment_code),
  KEY idx_shipments_customer_id (customer_id),
  KEY idx_shipments_category_id (category_id),
  KEY idx_shipments_status (shipment_status),
  KEY idx_shipments_payment_status (payment_status),
  KEY idx_shipments_scheduled_pickup_at (scheduled_pickup_at),
  KEY idx_shipments_created_at (created_at),
  KEY idx_shipments_deleted_at (deleted_at),
  CONSTRAINT fk_shipments_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_shipments_category_id FOREIGN KEY (category_id) REFERENCES shipment_categories (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_shipments_approved_by_user_id FOREIGN KEY (approved_by_user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_shipments_cancelled_by_user_id FOREIGN KEY (cancelled_by_user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_shipments_vehicle_preference CHECK (vehicle_preference IS NULL OR vehicle_preference IN ('bike', 'mini_truck', 'truck', 'heavy_truck', 'refrigerated_truck', 'van')),
  CONSTRAINT chk_shipments_status CHECK (shipment_status IN ('pending', 'approved', 'assigned', 'accepted', 'pickup_completed', 'in_transit', 'delivered', 'completed', 'cancelled', 'rejected')),
  CONSTRAINT chk_shipments_payment_status CHECK (payment_status IN ('unpaid', 'pending', 'paid', 'failed', 'refunded', 'cancelled')),
  CONSTRAINT chk_shipments_package_weight CHECK (package_weight_kg > 0),
  CONSTRAINT chk_shipments_estimated_price CHECK (estimated_price >= 0),
  CONSTRAINT chk_shipments_estimated_distance CHECK (estimated_distance_km IS NULL OR estimated_distance_km >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
