USE cargoconnect_db;

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_code VARCHAR(40) NOT NULL,
  shipment_id BIGINT UNSIGNED NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  payment_method VARCHAR(30) NOT NULL,
  payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  currency CHAR(3) NOT NULL DEFAULT 'INR',
  subtotal_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  fee_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  transaction_reference VARCHAR(120) NULL,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  refunded_at TIMESTAMP NULL DEFAULT NULL,
  failure_reason VARCHAR(255) NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payments_payment_code (payment_code),
  UNIQUE KEY uq_payments_transaction_reference (transaction_reference),
  KEY idx_payments_shipment_id (shipment_id),
  KEY idx_payments_customer_id (customer_id),
  KEY idx_payments_status_method (payment_status, payment_method),
  KEY idx_payments_created_at (created_at),
  KEY idx_payments_deleted_at (deleted_at),
  CONSTRAINT fk_payments_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_payments_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_payments_method CHECK (payment_method IN ('upi', 'card', 'cash', 'wallet', 'bank_transfer')),
  CONSTRAINT chk_payments_status CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded', 'cancelled')),
  CONSTRAINT chk_payments_amounts CHECK (subtotal_amount >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND fee_amount >= 0 AND total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
