USE cargoconnect_db;

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_number VARCHAR(50) NOT NULL,
  shipment_id BIGINT UNSIGNED NOT NULL,
  payment_id BIGINT UNSIGNED NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  invoice_status VARCHAR(20) NOT NULL DEFAULT 'generated',
  payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
  billing_name VARCHAR(120) NOT NULL,
  billing_email VARCHAR(160) NULL,
  billing_phone VARCHAR(30) NULL,
  billing_address TEXT NULL,
  subtotal_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  due_at TIMESTAMP NULL DEFAULT NULL,
  pdf_url VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_invoices_invoice_number (invoice_number),
  KEY idx_invoices_shipment_id (shipment_id),
  KEY idx_invoices_payment_id (payment_id),
  KEY idx_invoices_customer_id (customer_id),
  KEY idx_invoices_status (invoice_status, payment_status),
  KEY idx_invoices_issued_at (issued_at),
  KEY idx_invoices_deleted_at (deleted_at),
  CONSTRAINT fk_invoices_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_payment_id FOREIGN KEY (payment_id) REFERENCES payments (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_invoices_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_invoices_status CHECK (invoice_status IN ('draft', 'generated', 'void')),
  CONSTRAINT chk_invoices_payment_status CHECK (payment_status IN ('unpaid', 'pending', 'paid', 'failed', 'refunded', 'cancelled')),
  CONSTRAINT chk_invoices_amounts CHECK (subtotal_amount >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
