USE cargoconnect_db;

CREATE TABLE IF NOT EXISTS proof_uploads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  proof_code VARCHAR(40) NOT NULL,
  shipment_id BIGINT UNSIGNED NOT NULL,
  assignment_id BIGINT UNSIGNED NULL,
  uploaded_by_driver_id BIGINT UNSIGNED NULL,
  proof_type VARCHAR(30) NOT NULL,
  file_url VARCHAR(500) NOT NULL,
  file_name VARCHAR(255) NULL,
  file_mime_type VARCHAR(120) NULL,
  file_size_bytes BIGINT UNSIGNED NULL,
  notes TEXT NULL,
  location_text VARCHAR(255) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  verification_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  verified_by_user_id BIGINT UNSIGNED NULL,
  verified_at TIMESTAMP NULL DEFAULT NULL,
  captured_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_proof_uploads_proof_code (proof_code),
  KEY idx_proof_uploads_shipment_type (shipment_id, proof_type),
  KEY idx_proof_uploads_assignment_id (assignment_id),
  KEY idx_proof_uploads_driver_id (uploaded_by_driver_id),
  KEY idx_proof_uploads_verification_status (verification_status),
  KEY idx_proof_uploads_deleted_at (deleted_at),
  CONSTRAINT fk_proof_uploads_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_proof_uploads_assignment_id FOREIGN KEY (assignment_id) REFERENCES assignments (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_proof_uploads_uploaded_by_driver_id FOREIGN KEY (uploaded_by_driver_id) REFERENCES drivers (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_proof_uploads_verified_by_user_id FOREIGN KEY (verified_by_user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_proof_uploads_type CHECK (proof_type IN ('pickup', 'delivery', 'damage', 'invoice', 'other')),
  CONSTRAINT chk_proof_uploads_verification_status CHECK (verification_status IN ('pending', 'verified', 'rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
