USE cargoconnect_db;

CREATE TABLE IF NOT EXISTS fuel_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_code VARCHAR(40) NOT NULL,
  driver_id BIGINT UNSIGNED NOT NULL,
  vehicle_id BIGINT UNSIGNED NULL,
  assignment_id BIGINT UNSIGNED NULL,
  fuel_amount_liters DECIMAL(10,2) NOT NULL,
  bill_amount DECIMAL(10,2) NOT NULL,
  fuel_station VARCHAR(160) NOT NULL,
  bill_file_url VARCHAR(500) NULL,
  notes TEXT NULL,
  request_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL DEFAULT NULL,
  review_notes VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_fuel_requests_request_code (request_code),
  KEY idx_fuel_requests_driver_status (driver_id, request_status),
  KEY idx_fuel_requests_vehicle_id (vehicle_id),
  KEY idx_fuel_requests_assignment_id (assignment_id),
  KEY idx_fuel_requests_reviewed_by_user_id (reviewed_by_user_id),
  KEY idx_fuel_requests_created_at (created_at),
  KEY idx_fuel_requests_deleted_at (deleted_at),
  CONSTRAINT fk_fuel_requests_driver_id FOREIGN KEY (driver_id) REFERENCES drivers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_fuel_requests_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_fuel_requests_assignment_id FOREIGN KEY (assignment_id) REFERENCES assignments (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_fuel_requests_reviewed_by_user_id FOREIGN KEY (reviewed_by_user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_fuel_requests_status CHECK (request_status IN ('pending', 'approved', 'rejected', 'paid')),
  CONSTRAINT chk_fuel_requests_amounts CHECK (fuel_amount_liters > 0 AND bill_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
