USE cargoconnect_db;

CREATE TABLE IF NOT EXISTS emergency_reports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  report_code VARCHAR(40) NOT NULL,
  driver_id BIGINT UNSIGNED NOT NULL,
  vehicle_id BIGINT UNSIGNED NULL,
  assignment_id BIGINT UNSIGNED NULL,
  shipment_id BIGINT UNSIGNED NULL,
  report_type VARCHAR(40) NOT NULL,
  severity VARCHAR(20) NOT NULL DEFAULT 'medium',
  description TEXT NOT NULL,
  attachment_url VARCHAR(500) NULL,
  location_text VARCHAR(255) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  report_status VARCHAR(20) NOT NULL DEFAULT 'open',
  resolved_by_user_id BIGINT UNSIGNED NULL,
  resolved_at TIMESTAMP NULL DEFAULT NULL,
  resolution_notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_emergency_reports_report_code (report_code),
  KEY idx_emergency_reports_driver_status (driver_id, report_status),
  KEY idx_emergency_reports_vehicle_id (vehicle_id),
  KEY idx_emergency_reports_assignment_id (assignment_id),
  KEY idx_emergency_reports_shipment_id (shipment_id),
  KEY idx_emergency_reports_severity (severity),
  KEY idx_emergency_reports_created_at (created_at),
  KEY idx_emergency_reports_deleted_at (deleted_at),
  CONSTRAINT fk_emergency_reports_driver_id FOREIGN KEY (driver_id) REFERENCES drivers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_emergency_reports_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_emergency_reports_assignment_id FOREIGN KEY (assignment_id) REFERENCES assignments (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_emergency_reports_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_emergency_reports_resolved_by_user_id FOREIGN KEY (resolved_by_user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_emergency_reports_type CHECK (report_type IN ('accident', 'breakdown', 'route_blocked', 'medical', 'security', 'other')),
  CONSTRAINT chk_emergency_reports_severity CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  CONSTRAINT chk_emergency_reports_status CHECK (report_status IN ('open', 'in_review', 'resolved', 'closed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
