USE cargoconnect_db;

CREATE TABLE IF NOT EXISTS support_issues (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  issue_code VARCHAR(40) NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  shipment_id BIGINT UNSIGNED NULL,
  issue_type VARCHAR(40) NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'medium',
  subject VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  attachment_url VARCHAR(500) NULL,
  attachment_file_name VARCHAR(255) NULL,
  attachment_mime_type VARCHAR(120) NULL,
  attachment_size_bytes BIGINT UNSIGNED NULL,
  issue_status VARCHAR(20) NOT NULL DEFAULT 'open',
  admin_response TEXT NULL,
  responded_by_user_id BIGINT UNSIGNED NULL,
  responded_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_support_issues_issue_code (issue_code),
  KEY idx_support_issues_customer_status (customer_id, issue_status),
  KEY idx_support_issues_shipment_id (shipment_id),
  KEY idx_support_issues_priority (priority),
  KEY idx_support_issues_created_at (created_at),
  KEY idx_support_issues_deleted_at (deleted_at),
  CONSTRAINT fk_support_issues_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_support_issues_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_support_issues_responded_by_user_id FOREIGN KEY (responded_by_user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_support_issues_type CHECK (issue_type IN ('booking', 'payment', 'driver', 'delay', 'damage', 'invoice', 'other')),
  CONSTRAINT chk_support_issues_priority CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  CONSTRAINT chk_support_issues_status CHECK (issue_status IN ('open', 'in_review', 'resolved', 'closed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS feedback (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  feedback_code VARCHAR(40) NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  shipment_id BIGINT UNSIGNED NULL,
  rating TINYINT UNSIGNED NOT NULL,
  experience_tags JSON NULL,
  comments TEXT NULL,
  would_recommend TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_feedback_feedback_code (feedback_code),
  UNIQUE KEY uq_feedback_customer_shipment (customer_id, shipment_id),
  KEY idx_feedback_customer_id (customer_id),
  KEY idx_feedback_shipment_id (shipment_id),
  KEY idx_feedback_rating (rating),
  KEY idx_feedback_created_at (created_at),
  KEY idx_feedback_deleted_at (deleted_at),
  CONSTRAINT fk_feedback_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_feedback_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_feedback_rating CHECK (rating BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS breakdown_reports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  breakdown_code VARCHAR(40) NOT NULL,
  driver_id BIGINT UNSIGNED NOT NULL,
  vehicle_id BIGINT UNSIGNED NULL,
  assignment_id BIGINT UNSIGNED NULL,
  shipment_id BIGINT UNSIGNED NULL,
  issue_type VARCHAR(60) NOT NULL,
  severity VARCHAR(20) NOT NULL DEFAULT 'medium',
  description TEXT NOT NULL,
  attachment_url VARCHAR(500) NULL,
  attachment_file_name VARCHAR(255) NULL,
  attachment_mime_type VARCHAR(120) NULL,
  attachment_size_bytes BIGINT UNSIGNED NULL,
  location_text VARCHAR(255) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  report_status VARCHAR(20) NOT NULL DEFAULT 'open',
  assistance_requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_by_user_id BIGINT UNSIGNED NULL,
  resolved_at TIMESTAMP NULL DEFAULT NULL,
  resolution_notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_breakdown_reports_breakdown_code (breakdown_code),
  KEY idx_breakdown_reports_driver_status (driver_id, report_status),
  KEY idx_breakdown_reports_vehicle_id (vehicle_id),
  KEY idx_breakdown_reports_assignment_id (assignment_id),
  KEY idx_breakdown_reports_shipment_id (shipment_id),
  KEY idx_breakdown_reports_severity (severity),
  KEY idx_breakdown_reports_created_at (created_at),
  KEY idx_breakdown_reports_deleted_at (deleted_at),
  CONSTRAINT fk_breakdown_reports_driver_id FOREIGN KEY (driver_id) REFERENCES drivers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_breakdown_reports_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_breakdown_reports_assignment_id FOREIGN KEY (assignment_id) REFERENCES assignments (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_breakdown_reports_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_breakdown_reports_resolved_by_user_id FOREIGN KEY (resolved_by_user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_breakdown_reports_severity CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  CONSTRAINT chk_breakdown_reports_status CHECK (report_status IN ('open', 'in_review', 'resolved', 'closed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
